spring:
  datasource:
    password: sol123
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres

server:
    port: 9093
#    servlet:
#        #jetty
#        contextPath: "/api/*" 
#        #tomcat
#        context-path: "/api"
        
jwt:
  token:
    secret-key: 62Uvm9DxePvfeU2e
    expire-length-minutos: 720
  token-refresh:
    expire-length-minutos: 10080